import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Qurbonov.uz",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/favicon.ico",
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="w-screen h-screen bg-sky-900"> */}
        <div className=" bg-gradient-to-tr from-sky-700  via-blue-800 to-indigo-900 ">
          {/* <div className="w-screen h-screen bg-gradient-to-tl from-sky-900 to-indigo-900"> */}
          {/* <div className="w-screen h-screen bg-gradient-to-b from-sky-900 to-sky-600"> */}
          {/* <div className="w-screen h-screen bg-gradient-to-b from-slate-300 to-slate-100"> */}
          <div className="h-24">
            <Navbar />
          </div>
          <div className="h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
